version: “3.8”

services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_store
    ports:
      - "5433:5432"
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=rootuser
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_store
      - MYSQL_PORT=3306
    ports:
      - "33306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USER=rootuser
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - 8080:80
